[package]
name = "tiny-adnl"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@dexpa.io>"]
edition = "2018"

[dependencies]
aes = { version = "0.7", features = ["ctr"] }
async-trait = "0.1"
anyhow = "1.0"
base64 = "0.13"
curve25519-dalek-ng = "4.0"
crossbeam-queue = "0.3"
dashmap = "4.0"
generic-array = "0.14"
hex = "0.4"
log = "0.4"
libc = "0.2"
parking_lot = "0.11"
rand = "0.8"
rustc-hash = "1.1.0"
serde = "1.0"
sha2 = "0.9"
smallvec = { version = "1.6.1", features = ["union", "const_generics"] }
thiserror = "1.0"
tokio = { version = "1.6", features = ["sync", "net", "rt", "time", "io-util", "macros"] }
tokio-io-timeout = "1.1.1"
x25519-dalek-ng = "1.1"

ed25519-consensus = "1.0.0"
raptorq = { git = "https://github.com/Rexagon/raptorq.git" }

ton_types = { git = "https://github.com/broxus/ton-labs-types" }

[dependencies.ton_api]
git = "https://github.com/broxus/ton-labs-tl.git"
package = "ton_api"
default-features = false
features = ["ton_api"]

[features]
asm = ["sha2/asm",  "ton_types/asm"]
